name: CI_IEA15

# We run CI on push commits and pull requests on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        # https://github.com/marketplace/actions/setup-miniconda
        with:
          miniconda-version: "latest"
          channels: conda-forge
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: tests/environment.yml
          activate-environment: "test"
    

      # Install WEIO
      - name: Install WEIO
        shell: bash -l {0}
        run: |
          git clone https://github.com/ebranlard/weio
          cd weio
          python -m pip install -e .

      # Debugging session
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3

      # Run all tests
      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest tests

      # Run WISDEM analysis script
      - name: Run WISDEM script
        shell: bash -l {0}
        run: |
          cd WISDEM
          python run_model.py

      # Run OpenFAST monopile-ROSCO
      - name: Run OpenFAST fixed-bottom with ROSCO
        shell: bash -l {0}
        run: |
          cd OpenFAST/IEA-15-240-RWT-Monopile
          sed --separate --in-place=BAK 's/300.0 \{1,\} TMax/10.0    TMax/' IEA-15-240-RWT-Monopile.fst
          openfast IEA-15-240-RWT-Monopile.fst

      # Run OpenFAST floating
      - name: Run OpenFAST floating
        shell: bash -l {0}
        run: |
          cd OpenFAST/IEA-15-240-RWT-UMaineSemi
          openfast IEA-15-240-RWT-UMaineSemi.fst

      # Run OpenFAST monopile-DTU
      #- name: Run OpenFAST fixed-bottom with DTU controller
      #  shell: bash -l {0}
      #  run: |
      #    cd OpenFAST/IEA-15-240-RWT-Monopile_wDTUcontroller
      #    sed --separate --in-place=BAK 's/300.0 \{1,\} TMax/10.0    TMax/' IEA-15-240-RWT-Monopile_wDTUcontroller.fst
      #    openfast IEA-15-240-RWT-Monopile_wDTUcontroller.fst

      # Run OpenFAST monopile-OLAF
      - name: Run OpenFAST fixed-bottom with OLAF
        shell: bash -l {0}
        run: |
          cd OpenFAST/IEA-15-240-RWT-OLAF
          sed --separate --in-place=BAK 's/300.0 \{1,\} TMax/0.25    TMax/' IEA-15-240-RWT_OLAF.fst
          openfast IEA-15-240-RWT_OLAF.fst
